In [2]:
# Imports
import pandas as pd
from pathlib import Path
import coloc_transform

In [3]:
# Load Summary Statistics Data
input_file_path = Path("/mnt/working/locus_reports/qtl/eqtl/eqtlgen/cis/2019-12-11-cis-eQTLsFDR0.05-ProbeLevel-CohortInfoRemoved-BonferroniAdded.txt.gz")  # Replace with your actual file path
header_lines = 0  # Adjust based on your file's header lines
df = coloc_transform.load_input_data(input_file_path, header_lines)

# Print the shape of the DataFrame
print(f"DataFrame shape: {df.shape}")

# Print the column names of the DataFrame
print(f"Column names: {df.columns.tolist()}")

# Display the first few rows of the DataFrame
df.head()

DataFrame shape: (10507664, 15)
Column names: ['Pvalue', 'SNP', 'SNPChr', 'SNPPos', 'AssessedAllele', 'OtherAllele', 'Zscore', 'Gene', 'GeneSymbol', 'GeneChr', 'GenePos', 'NrCohorts', 'NrSamples', 'FDR', 'BonferroniP']

,Pvalue,SNP,SNPChr,SNPPos,AssessedAllele,OtherAllele,Zscore,Gene,GeneSymbol,GeneChr,GenePos,NrCohorts,NrSamples,FDR,BonferroniP
0,3.271700e-310,rs12230244,12,10117369,T,A,200.7534,ENSG00000172322,CLEC12A,12,10126104,34,30596,0.0,4.166200e-302
1,3.271700e-310,rs12229020,12,10117683,G,C,200.6568,ENSG00000172322,CLEC12A,12,10126104,34,30596,0.0,4.166200e-302
2,3.271700e-310,rs61913527,12,10116198,T,C,200.2654,ENSG00000172322,CLEC12A,12,10126104,34,30598,0.0,4.166200e-302
3,3.271700e-310,rs2594103,12,10115428,T,C,200.0420,ENSG00000172322,CLEC12A,12,10126104,34,30598,0.0,4.166200e-302
4,3.271700e-310,rs12231833,12,10118428,A,G,199.9508,ENSG00000172322,CLEC12A,12,10126104,34,30592,0.0,4.166200e-302

In [3]:
# Configuration
chr_col = "chromosome"
pos_col = "snpLocation"
rsid_col = "snpid" # Set to None if not available
gene_id_col = "gene" # Set to None if not available
effect_allele_col = "A2" # Set to None if not available
non_effect_allele_col = "A1" # Set to None if not available
n_col = None # Set to None if not available
maf_col = "A2freq" # Set to None if not available
mac_col = None # Set to None if not available
p_col = "pvalue" # Set to None if not available
statistic_col = "statistic" # Set to None if not available
se_col = None # Set to None if not available
beta_col = "beta" # Set to None if not available
var_beta_col = None # Set to None if not available
sdY_col = None # Set to None if not available

In [4]:
df[chr_col] = df[chr_col].astype(str).apply(coloc_transform.normalize_chromosome)

In [5]:
expanded_ranges_fp = Path('/mnt/working/locus_reports/expanded_locus_ranges_by_chromosome.json')
expanded_ranges = coloc_transform.load_expanded_ranges(expanded_ranges_fp)
# Filter the DataFrame by expanded ranges
filtered_df = coloc_transform.filter_by_expanded_ranges(
    df=df,
    chr_col=chr_col,
    pos_col=pos_col,
    expanded_ranges=expanded_ranges
)

# Print the shape of the DataFrame
print(f"DataFrame shape: {filtered_df.shape}")

# Print the column names of the DataFrame
print(f"Column names: {filtered_df.columns.tolist()}")

# Display the first few rows of the DataFrame
filtered_df.head()

DataFrame shape: (4618618, 17)
Column names: ['chromosome', 'snpLocation', 'snpid', 'gene', 'geneSymbol', 'statistic', 'pvalue', 'FDR', 'beta', 'A1', 'A2', 'A2freq', 'expressionIncreasingAllele', 'strand', 'geneBiotype', 'geneStartPosition', 'geneEndPosition']

,chromosome,snpLocation,snpid,gene,geneSymbol,statistic,pvalue,FDR,beta,A1,A2,A2freq,expressionIncreasingAllele,strand,geneBiotype,geneStartPosition,geneEndPosition
1798908,1,52227853,rs12062229,ENSG00000185104,FAF1,-0.103625,0.917503,0.990445,-0.008742,G,A,0.169444,G,-1,protein_coding,50437028,50960263
1798909,1,52228123,rs80021891,ENSG00000185104,FAF1,-0.405033,0.685606,0.953234,-0.044951,C,T,0.078288,C,-1,protein_coding,50437028,50960263
1798910,1,52230197,rs72900013,ENSG00000185104,FAF1,0.540007,0.589405,0.929601,0.048612,A,G,0.139872,G,-1,protein_coding,50437028,50960263
1798911,1,52232619,rs9919140,ENSG00000185104,FAF1,-0.051794,0.958711,0.995153,-0.004350,A,G,0.174956,A,-1,protein_coding,50437028,50960263
1798912,1,52234339,rs61374814,ENSG00000185104,FAF1,0.598215,0.549936,0.919090,0.053691,A,G,0.144380,G,-1,protein_coding,50437028,50960263

In [6]:
annotated_df = coloc_transform.annotate_sum_stats(
    df=filtered_df,
    chr_col=chr_col,
    pos_col=pos_col,
    rsid_col=rsid_col,
    effect_allele_col=effect_allele_col,
    non_effect_allele_col=non_effect_allele_col,
    n_col=n_col,
    maf_col=maf_col,
    mac_col=mac_col,
    p_col=p_col,
    statistic_col=statistic_col,
    se_col=se_col,
    beta_col=beta_col,
    var_beta_col=var_beta_col,
    sdY_col=sdY_col
)

Error: GLOBAL_MAFS not found in record for rsID rs563775205
fetch_rsid_records: reached max retries, returning empty result for rsids: r - 8
fetch_rsid_records: reached max retries, returning empty result for rsids: r - 8
Error: GLOBAL_MAFS not found in record for rsID rs572410793
Error: GLOBAL_MAFS not found in record for rsID rs117601013
fetch_rsid_records: reached max retries, returning empty result for rsids: r - 5
Error: GLOBAL_MAFS not found in record for rsID rs140809073
fetch_rsid_records: reached max retries, returning empty result for rsids: r - 7
fetch_rsid_records: reached max retries, returning empty result for rsids: r - 2
fetch_rsid_records: reached max retries, returning empty result for rsids: r - 7
fetch_rsid_records: reached max retries, returning empty result for rsids: r - 3

/mnt/working/scripts/coloc_transform.py:361: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  for start in range(0, len(rsids_full), batch_size):

In [ ]:
transformed_df = coloc_transform.transform_sum_stats(
        df=annotated_df,
        chr_col=chr_col,
        pos_col=pos_col,
        variant_id_col='Variant_ID',
        rsid_col=rsid_col or 'rsID',
        gene_id_col=gene_id_col,
        effect_allele_col=effect_allele_col or 'dbSNP_alt',
        non_effect_allele_col=non_effect_allele_col or 'dbSNP_ref',
        p_col=p_col or 'P',
        beta_col=beta_col or 'BETA',
        se_col=se_col or 'SE',
        n_col=n_col or 'N',
        maf_col=maf_col or 'MAF',
        var_beta_col=var_beta_col or 'VARBETA',
        sdY_col=sdY_col or 'SDY'
    )

transformed_df.head()

,CHR,BP,VARIANT_ID,RSID,GENE_ID,NON_EFFECT_ALLELE,EFFECT_ALLELE,P,BETA,VAR_BETA,SDY,SE,MAF,N
0,1,52227853,1:52227853:G:A,rs12062229,ENSG00000185104,G,A,0.917503,-0.008742,0.007117,NaN,-0.084364,0.169444,NaN
1,1,52228123,1:52228123:C:T,rs80021891,ENSG00000185104,C,T,0.685606,-0.044951,0.012317,NaN,-0.110982,0.078288,NaN
2,1,52230197,1:52230197:A:C,rs72900013,ENSG00000185104,A,G,0.589405,0.048612,0.008104,NaN,0.090022,0.139872,NaN
3,1,52232619,1:52232619:A:G,rs9919140,ENSG00000185104,A,G,0.958711,-0.004350,0.007055,NaN,-0.083996,0.174956,NaN
4,1,52234339,1:52234339:A:C,rs61374814,ENSG00000185104,A,G,0.549936,0.053691,0.008055,NaN,0.089752,0.144380,NaN

In [9]:
# Save the transformed data to a new file
output_dir = "/mnt/working/locus_reports/qtl/eqtl/coloc_ready" # Replace with your desired output file path
output_fn = input_file_path.stem + ".coloc_ready.tsv"
output_fp = Path(output_dir) / output_fn
transformed_df.to_csv(output_fp, sep="\t", index=False)